# Configure the values below with the values from your application
# You can create one at hhttp://www.facebook.com/developers/apps.php
app_id: 172433969471573
secret: b5681023f0f5e122fdfb8059d937fdd0
api_key: 1f0f966cec3df97e6ab95a7b1a356eaf
app_url: "http://creamfields.heroku.com" # No trailing slash
fb_app_url: "http://apps.facebook.com/creamfields_tab" # No trailing slash